apiVersion: v1
kind: Service
metadata:
  name: localhost
  labels:
    app: backendlab2mingeso
spec:
  type: LoadBalancer
  selector:
    app: backendlab2mingeso
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000
      port: 8000
      targetPort: 8000
